// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kutudkpplfgiyvmggejl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1dHVka3BwbGZnaXl2bWdnZWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTI1MDEsImV4cCI6MjA3MTI2ODUwMX0.J50E-Q-3CnmMME1Jp8Rj9TalhYqPFavSNzrd6Y7Qtb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});